apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "ElectrifAi_Logo_200px.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "electrifai-public", "product_id": "models", "partner_name": "ElectrifAi"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: Models
    version: "{{ .Values.nginx.image.tag }}"
    description: |-
      Why build when you can buy? Building and developing machine learning
      models takes time and effort. ElectrifAi delivers superior, fast and
      reliable results with over 1,000 ready-to-deploy machine learning
      models that seamlessly integrate into existing workflows.
      Proven commercial value in weeks, for high value use cases across
      all major verticals.

      # Support

      This image is built by Google. It is your responsibility to keep
      container images you run or store in your own repositories
      up to date with security patches.

      Please reach out to info@electrifai.net for support.
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'Electrifai website'
      url: https://electrifai.net/
    notes: |-
      # Aditional marketing notes

      Key Benefits: Rapid Time-to-Value, Reduce Cost, Minimize Risk, Increase Revenue
  info:
  - name: Nginx External IP
    type: Reference
    valueFrom:
      serviceRef:
        name: {{ .Release.Name }}-nginx-svc
        protocol: HTTPS
  - name: Application Namespace
    value: {{ .Release.Namespace }}
  - name: Nginx Configuration
    value: nginx-config.conf
  - name: Nginx Cert
    type: Reference
    valueFrom:
      secretKeyRef:
        key: https1.cert
        name: {{ .Release.Name }}-nginx-secret
  - name: Nginx Key
    type: Reference
    valueFrom:
      secretKeyRef:
        key: https1.key
        name: {{ .Release.Name }}-nginx-secret
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: apps/v1
    kind: Deployment
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
