apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lambda-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline_compilation_time: '2021-08-18T10:21:39.238559',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "<lambda>"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3}
spec:
  entrypoint: lambda
  templates:
  - name: lambda
    dag:
      tasks:
      - {name: yolo-model, template: yolo-model}
      - name: yolo-testing
        template: yolo-testing
        dependencies: [yolo-model]
  - name: yolo-model
    container:
      args: ['mkdir -p ./jupyter-work-dir/ && cd ./jupyter-work-dir/ && curl -H "Cache-Control:
          no-cache" -L https://raw.githubusercontent.com/elyra-ai/elyra/master/elyra/kfp/bootstrapper.py
          --output bootstrapper.py && curl -H "Cache-Control: no-cache" -L https://raw.githubusercontent.com/elyra-ai/elyra/master/etc/generic/requirements-elyra.txt
          --output requirements-elyra.txt && python3 -m pip install  packaging &&
          python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py
          --cos-endpoint http://minio-service.kubeflow.svc.cluster.local:9000/ --cos-bucket
          mlpipeline --cos-directory "yolo-0818102126" --cos-dependencies-archive
          "YOLO_model-b91e0ca8-038d-411d-b58b-ce873d603763.tar.gz" --file "YOLO-Object-Detection/YOLO_model.ipynb" ']
      command: [sh, -c]
      env:
      - {name: ELYRA_RUNTIME_ENV, value: kfp}
      - {name: AWS_ACCESS_KEY_ID, value: minio}
      - {name: AWS_SECRET_ACCESS_KEY, value: minio123}
      - name: ELYRA_ENABLE_PIPELINE_INFO
        value: "True"
      - {name: ELYRA_WRITABLE_CONTAINER_DIR, value: /tmp}
      - {name: ELYRA_RUN_NAME, value: '{{workflow.annotations.pipelines.kubeflow.org/run_name}}'}
      image: tensorflow/tensorflow:2.3.0-gpu
    outputs:
      artifacts:
      - {name: mlpipeline-metrics, path: /tmp/mlpipeline-metrics.json}
      - {name: mlpipeline-ui-metadata, path: /tmp/mlpipeline-ui-metadata.json}
    metadata:
      annotations: {elyra/node-file-name: YOLO-Object-Detection/YOLO_model.ipynb,
        elyra/pipeline-source: yolo.pipeline}
      labels: {elyra/node-type: notebook-script, elyra/pipeline-name: yolo, elyra/pipeline-version: '',
        elyra/experiment-name: '', elyra/node-name: YOLO_model, pipelines.kubeflow.org/kfp_sdk_version: 1.6.3,
        pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  - name: yolo-testing
    container:
      args: ['mkdir -p ./jupyter-work-dir/ && cd ./jupyter-work-dir/ && curl -H "Cache-Control:
          no-cache" -L https://raw.githubusercontent.com/elyra-ai/elyra/master/elyra/kfp/bootstrapper.py
          --output bootstrapper.py && curl -H "Cache-Control: no-cache" -L https://raw.githubusercontent.com/elyra-ai/elyra/master/etc/generic/requirements-elyra.txt
          --output requirements-elyra.txt && python3 -m pip install  packaging &&
          python3 -m pip freeze > requirements-current.txt && python3 bootstrapper.py
          --cos-endpoint http://minio-service.kubeflow.svc.cluster.local:9000/ --cos-bucket
          mlpipeline --cos-directory "yolo-0818102126" --cos-dependencies-archive
          "YOLO_testing-f646d8ca-97e6-4f8e-9790-2b0b5c1f0fff.tar.gz" --file "YOLO-Object-Detection/YOLO_testing.ipynb" ']
      command: [sh, -c]
      env:
      - {name: ELYRA_RUNTIME_ENV, value: kfp}
      - {name: AWS_ACCESS_KEY_ID, value: minio}
      - {name: AWS_SECRET_ACCESS_KEY, value: minio123}
      - name: ELYRA_ENABLE_PIPELINE_INFO
        value: "True"
      - {name: ELYRA_WRITABLE_CONTAINER_DIR, value: /tmp}
      - {name: ELYRA_RUN_NAME, value: '{{workflow.annotations.pipelines.kubeflow.org/run_name}}'}
      image: tensorflow/tensorflow:2.3.0-gpu
    outputs:
      artifacts:
      - {name: mlpipeline-metrics, path: /tmp/mlpipeline-metrics.json}
      - {name: mlpipeline-ui-metadata, path: /tmp/mlpipeline-ui-metadata.json}
    metadata:
      annotations: {elyra/node-file-name: YOLO-Object-Detection/YOLO_testing.ipynb,
        elyra/pipeline-source: yolo.pipeline}
      labels: {elyra/node-type: notebook-script, elyra/pipeline-name: yolo, elyra/pipeline-version: '',
        elyra/experiment-name: '', elyra/node-name: YOLO_testing, pipelines.kubeflow.org/kfp_sdk_version: 1.6.3,
        pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
