---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-configmap
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: nginx-server
data:
  nginx-config.conf: |
   ssl_certificate      certs/https1.cert;
   ssl_certificate_key  certs/https1.key;
   server {
      listen 80;
      listen 443 ssl;
      listen 8080;
      server_name www.my-webserver.com;
      location / {
               index index.html;
               root /usr/share/nginx/html;
      }
      location /stub_status {
      stub_status on;
      access_log off;
      allow 127.0.0.1;
      deny all;
      }
      location = /favicon.ico {
               error_page 404 = @empty;
      }
      location @empty {
               empty_gif;
      }
    }
